### ISSUE TITLE
Change logo with the new one

### ISSUE THREAD

**Issue by ClementMayer** [Substra/substra-frontend#55]
Upload the new logo 
![Substra Foundation_Logo horizontal](https://user-images.githubusercontent.com/54810898/83848245-d51bbe00-a70d-11ea-90d8-f58f1c4c5d26.png)

**Comment by jmorel** [comment]
@ClementMayer Could you provide the SVG for this?

Also for @maeldebon we'll need to extract only the triangle part for the favicon.

**Comment by ClementMayer** [comment]
Could you try with this one? I havent got the horizontal on SVG but this one should be ok. 
[Substra_Logo couleur_RVB.svg.zip](https://github.com/SubstraFoundation/substra-frontend/files/5069073/Substra_Logo.couleur_RVB.svg.zip)

**Comment by jmorel** [comment]
The vertical logo won't fit into the layout. I'll try to modify the SVG you gave me so that it is horizontal and then provide it to @maeldebon.

**Comment by jmorel** [comment]
[Substra logo new.zip](https://github.com/SubstraFoundation/substra-frontend/files/5069408/Substra.logo.new.zip)

@maeldebon here are the SVG for the horizontal logo and all of the favicons. I included 2 versions of the horizontal logo: one with whitespace and one without. I think the one without should be the one to be included.

**Comment by maeldebon** [comment]
Alright, thanks!

**Comment by jmorel** [comment]
@ClementMayer It looks like the SVG you gave me declares the text as SVG shapes but the triangle itself is actually a PNG image. Do you have a full-shape version available ? Even one without text is fine, I'll assemble them together.

**Comment by ClementMayer** [comment]
Could you tell me if this one is ok? 
[Substra_Sigle couleur_RVB.svg.zip](https://github.com/SubstraFoundation/substra-frontend/files/5082925/Substra_Sigle.couleur_RVB.svg.zip)

**Comment by jmorel** [comment]
It's the same thing, it's actually an inlined JPEG within a SVG with SVG white shapes on top of it.

**Comment by ClementMayer** [comment]
Ok so I need to wait the Graphical designer at the end of August.

**Comment by jmorel** [comment]
No worries, let me know then!
