### ISSUE TITLE
Use Css Props from @emotion/core

### ISSUE THREAD

**Issue by GuillaumeCisco** [Substra/substra-frontend#9]
https://github.com/SubstraFoundation/substrafront/pull/45
https://github.com/SubstraFoundation/substrafront/pull/71
https://github.com/SubstraFoundation/substrafront/pull/72

**Comment by GuillaumeCisco** [comment]
Interesting to see how your company rewrites the git history of this project.
The [first commit](https://github.com/Substra/substra-frontend/commit/7392b459b9b124a91abd08a2bcbf3c8da00b6852) displays the date `Apr 29, 2021`

This issue is from `Jan 8, 2019`.
More than two years of code and contributors participation have been deleted.


It is great to go open source, better to respect your employees.

**Comment by alexisdeh** [comment]
The frontend was completely rewritten in April 2021 from scratch.
The legacy app and all related commits have not been deleted and are still [publicly available](https://github.com/Substra/substra-frontend/tree/master).

**Comment by GuillaumeCisco** [comment]
Actually, this is far more deceitful than I though.
A new `main` branch was created with an initial commit.

Leading to a misleading of the contributors: https://github.com/Substra/substra-frontend/graphs/contributors
And a misleading of the dates.
